### ISSUE TITLE
Todo before 0.4.x release

### ISSUE THREAD

**Issue by Gagaro** [makinacorpus/django-safedelete#43]
- [x] Doc for post_*delete signals
- [x] fix #41
- [x] take a look at #16
- [x] remove Django 1.4 => 1.7 support and clean code.
- [x] Add DELETED_VISIBLE_BY_FIELD
- [x] Add SOFT_DELETE_CASCADE
- [ ] Check the doc is up to date.

**Comment by Gagaro** [comment]
I think I'm gonna drop Django 1.4 to 1.7 support for the 0.4.x branch. This will allow to clean the code and fix #16.

Furthermore, these version of Django are no longer maintained.

**Comment by Gagaro** [comment]
Did someone had the opportunity to test the 0.4 branch in production? I wan't be able to do it before a while and would prefer to release it after it has been tested.

**Comment by AndreasBackx** [comment]
Is it possible to already make the docs available for 0.4.x? Regarding the docs, is it possible to add the index page to the sidebar too, it's a bit odd to not have some kind of "Introduction" or "Read me" in the sidebar and that you have to click the header.

![No index in sidebar](https://i.imgur.com/HvZEWOp.png)

**Comment by Gagaro** [comment]
Hi,

Thanks for all the feedback, due to the holiday I won't have time to answer precisely to each one of your issue for the moment, but I agree with you on each.

I'm still waiting for some kind of feedback for the 0.4 release, I never used it in production myself and didn't hear from anybody about it. But I think I'll release it some times in january anyway, there was some issue again with the 0.3.x.

**Comment by robermorales** [comment]
I have test it the branch 0.4.x and seems very stable!! I am looking forward the 0.4.x release, and I will use it in production, since I would not pin a github branch in a requirements.txt :)

**Comment by Gagaro** [comment]
Thanks for the feedback, I'm going to merge the last PR and do what's left in order to release it.

**Comment by Gagaro** [comment]
I just realise I don't actually own the project on RTD. I'll release the 0.4.0 without the doc for now.

**Comment by Gagaro** [comment]
Well I hope I didn't forget anything, 0.4.0 is officially released.
